defaultSemverRangePrefix: ""

nmMode: hardlinks-local

nodeLinker: pnp

packageExtensions:
  "@storybook/addon-essentials@*":
    dependencies:
      "@babel/core": "latest"
  "@mui/material@*":
    dependencies:
      "react-dom": "latest"
  "@storybook/react-vite@*":
    dependencies:
      "react-dom": "latest"
  "@storybook/react@*":
    dependencies:
      "react-dom": "latest"
      "require-from-string": "latest"
  "@design-systems/utils@*":
    dependencies:
      "react-dom": "latest"
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "latest"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "latest"
  "babel-loader@*":
    dependencies:
      "@babel/core": "latest"
      "webpack": "^5"
  "@storybook/addons@*":
    dependencies:
      "react-dom": "latest"
      "react": "latest"
  "react-colorful@*":
    dependencies:
      "react-dom": "latest"
  "@storybook/core-common@*":
    dependencies:
      "react-dom": "latest"
      "react": "latest" 
  "@storybook/client-api@*":
    dependencies:
      "react": "latest"
      "react-dom": "latest"
  "@storybook/source-loader@*":
    dependencies:
      "react": "latest"
      "react-dom": "latest"
  "@joshwooding/vite-plugin-react-docgen-typescript@*":
    dependencies:
      "typescript": "4.8.3"
  "@storybook/core-server@*":
    dependencies:
      "react-dom": "latest"
      "react": "latest" 
  "jscodeshift@*":
    dependencies:
      "@babel/preset-env": "latest"
  "@storybook/store@*":
    dependencies:
      "react-dom": "latest"
      "react": "latest"
  "@mdx-js/react@*":
    dependencies:
      "react": "latest"
      
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
